### PR TITLE
feat: filter __in

### PR DESCRIPTION
**Pull request by JakNowy**
# Pull Request Template for FastCRUD

## Description
This PR adds support for in_ filtering in crud methods like FastCRUD.select(item_id__in=[1,2]).

## Changes
Extended parse_filters method with addtional elif op == "in", mapping to sqlalchemy/sqlmodel or() filter.

## Tests
Added a test to test_parse_filters for both sqlalchemy and sqlmodel.

## Checklist
- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have added necessary documentation (if appropriate).
- [x] I have added tests that cover my changes (if applicable).
- [x] All new and existing tests passed.

## Additional Notes
I was trying to acomplish something similar for or_() but it turned out to be too complex for now.

### CODE REVIEW

**Comment by igorbenav** [comment]
Hey, @JakNowy, thanks for another great PR🎉!
Could you please add an example using `__in` to a docstring somewhere? I think adding `not_in` would be good as well. How did you think about adding `or`?

**Comment by igorbenav** [comment]
@JakNowy did you get a chance to take a look at this?

**Comment by JakNowy** [comment]
Hey @igorbenav not yet, but I will definetely add some more docs and `not_in` support soon! For `or`, I was thinking about nesting the _parse_filters() method in that case to produce something like or_(parsed_filter1, parsed_filter2).

**Comment by JakNowy** [comment]
Added `not_in` support and tests. Although quite simple, looks decent to me. Added short docstring for each fastcrud method, would you like me to extend the docs somewhere else? @igorbenav

**Comment by igorbenav** [comment]
> For `or`, I was thinking about nesting the _parse_filters() method in that case to produce something like or_(parsed_filter1, parsed_filter2).

I'll create another issue for the missing comparison operators, we can handle it there. Thanks for the pr!

**Pull request merged**
